baseurl = "/./" 
publishDir = "./"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "My R Blog"
theme = "hugo-tranquilpeak-theme-master"
googleAnalytics = ""
disqusShortname = "Heike"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Heike W"
  job = "Data Analyst/Data Scientist"
  location = "Germany"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  #gravatarEmail = "please-do-not-write-me@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "source/assets/img/me.jpg"
  # Your Twitter username without the @. E.g : tranquilpeak
  twitter = "betamaus"



[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 1
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 2
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 3
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 4
  identifier = "search"
  name = "Search"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-search\"></i>"
  url = "/#search"
  class = "st-search-show-outputs"
[[menu.main]]
  weight = 4
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"
[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/hWolters"

[params]
    description = "My blog about R built through Hugo and blogdown."
    sidebarBehavior = 1
    coverImage = "source/assets/img/banner"


    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    dateFormat = "2 January 2006"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"


    keywords = ["R", "R Studio", "Data Science", "Analtytics", "R Markdown","Research", "phd", "Text Minding", "Natural Language Processing"]

[params.header.rightLink]
  class = "open-algolia-search"
  icon = "search"
  url = "/#search"

[[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

[[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

